CREATE TABLE submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    question_id VARCHAR(255) NOT NULL,
    student_answer TEXT,
    correctness VARCHAR(255) NOT NULL,
    error_category VARCHAR(255),
    feedback TEXT,
    created_at TIMESTAMP(6)
);

CREATE TABLE submission_missing_keywords (
    submission_id BIGINT NOT NULL,
    keyword VARCHAR(255),
    CONSTRAINT fk_submission_missing_keywords_submission
        FOREIGN KEY (submission_id) REFERENCES submissions (id) ON DELETE CASCADE
);

CREATE INDEX idx_submissions_student_created
    ON submissions (student_id, created_at DESC);

CREATE INDEX idx_submission_missing_keywords_submission
    ON submission_missing_keywords (submission_id);
