CREATE TABLE submission_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    owner_role VARCHAR(16) NOT NULL,
    worksheet_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    source_type VARCHAR(16) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'UPLOADING',
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_submission_documents_owner CHECK (owner_user_id > 0),
    CONSTRAINT ck_submission_documents_worksheet CHECK (worksheet_id > 0),
    CONSTRAINT ck_submission_documents_student CHECK (student_id > 0),
    CONSTRAINT ck_submission_documents_owner_role CHECK (
        owner_role IN ('TUTOR', 'STUDENT')
    ),
    CONSTRAINT ck_submission_documents_source_type CHECK (
        source_type IN ('PDF', 'IMAGES')
    ),
    CONSTRAINT ck_submission_documents_status CHECK (
        status IN ('UPLOADING', 'READY')
    )
);

CREATE TABLE submission_pages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_document_id BIGINT NOT NULL,
    page_number INTEGER NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    media_type VARCHAR(64) NOT NULL,
    storage_key VARCHAR(255) NOT NULL,
    byte_size BIGINT NOT NULL,
    checksum_sha256 VARCHAR(64) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_submission_pages_storage_key UNIQUE (storage_key),
    CONSTRAINT uk_submission_pages_document_checksum UNIQUE (
        submission_document_id,
        checksum_sha256
    ),
    CONSTRAINT ck_submission_pages_number CHECK (page_number > 0),
    CONSTRAINT ck_submission_pages_filename CHECK (TRIM(original_filename) <> ''),
    CONSTRAINT ck_submission_pages_media_type CHECK (
        media_type IN ('application/pdf', 'image/jpeg', 'image/png')
    ),
    CONSTRAINT ck_submission_pages_storage_key CHECK (TRIM(storage_key) <> ''),
    CONSTRAINT ck_submission_pages_size CHECK (byte_size > 0),
    CONSTRAINT ck_submission_pages_checksum CHECK (
        LENGTH(checksum_sha256) = 64
        AND checksum_sha256 = LOWER(checksum_sha256)
    ),
    CONSTRAINT fk_submission_pages_document FOREIGN KEY (submission_document_id)
        REFERENCES submission_documents (id) ON DELETE CASCADE
);

CREATE INDEX idx_submission_documents_owner_created
    ON submission_documents (owner_user_id, created_at DESC);

CREATE INDEX idx_submission_documents_student_worksheet
    ON submission_documents (student_id, worksheet_id, created_at DESC);

CREATE INDEX idx_submission_pages_document_order
    ON submission_pages (submission_document_id, page_number, id);
