ALTER TABLE submissions RENAME COLUMN question_id TO legacy_question_reference;
ALTER TABLE submissions RENAME COLUMN student_answer TO extracted_answer;
ALTER TABLE submissions RENAME COLUMN correctness TO ai_suggested_outcome;
ALTER TABLE submissions RENAME COLUMN error_category TO ai_error_category;
ALTER TABLE submissions RENAME COLUMN feedback TO ai_suggested_feedback;

ALTER TABLE submissions ALTER COLUMN legacy_question_reference DROP NOT NULL;
ALTER TABLE submissions ALTER COLUMN ai_suggested_outcome DROP NOT NULL;

ALTER TABLE submissions ADD COLUMN submission_document_id BIGINT;
ALTER TABLE submissions ADD COLUMN worksheet_id BIGINT;
ALTER TABLE submissions ADD COLUMN worksheet_question_id BIGINT;
ALTER TABLE submissions ADD COLUMN question_bank_id BIGINT;
ALTER TABLE submissions ADD COLUMN model_answer_snapshot TEXT;
ALTER TABLE submissions ADD COLUMN max_marks DECIMAL(6, 2);
ALTER TABLE submissions ADD COLUMN ai_suggested_marks DECIMAL(6, 2);
ALTER TABLE submissions ADD COLUMN review_status VARCHAR(24) NOT NULL DEFAULT 'PENDING_REVIEW';
ALTER TABLE submissions ADD COLUMN approved_marks DECIMAL(6, 2);
ALTER TABLE submissions ADD COLUMN approved_feedback TEXT;
ALTER TABLE submissions ADD COLUMN reviewed_by_user_id BIGINT;
ALTER TABLE submissions ADD COLUMN reviewed_at TIMESTAMP(6);
ALTER TABLE submissions ADD COLUMN legacy_record BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE submissions ADD COLUMN updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE submissions ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

UPDATE submissions SET legacy_record = TRUE;
UPDATE submissions SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL;
ALTER TABLE submissions ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE submissions ALTER COLUMN created_at SET NOT NULL;

ALTER TABLE submissions
    ADD CONSTRAINT fk_submissions_document FOREIGN KEY (submission_document_id)
        REFERENCES submission_documents (id) ON DELETE RESTRICT;

ALTER TABLE submissions
    ADD CONSTRAINT uk_submissions_document_question UNIQUE (
        submission_document_id,
        worksheet_question_id
    );

ALTER TABLE submissions
    ADD CONSTRAINT ck_submissions_student CHECK (student_id > 0);

ALTER TABLE submissions
    ADD CONSTRAINT ck_submissions_reference_mode CHECK (
        (
            legacy_record = TRUE
            AND submission_document_id IS NULL
            AND legacy_question_reference IS NOT NULL
            AND TRIM(legacy_question_reference) <> ''
            AND worksheet_id IS NULL
            AND worksheet_question_id IS NULL
            AND question_bank_id IS NULL
            AND model_answer_snapshot IS NULL
            AND max_marks IS NULL
        )
        OR
        (
            legacy_record = FALSE
            AND submission_document_id IS NOT NULL
            AND legacy_question_reference IS NULL
            AND worksheet_id > 0
            AND worksheet_question_id > 0
            AND question_bank_id > 0
            AND model_answer_snapshot IS NOT NULL
            AND TRIM(model_answer_snapshot) <> ''
            AND max_marks > 0
        )
    );

ALTER TABLE submissions
    ADD CONSTRAINT ck_submissions_ai_marks CHECK (
        ai_suggested_marks IS NULL
        OR (
            max_marks IS NOT NULL
            AND ai_suggested_marks >= 0
            AND ai_suggested_marks <= max_marks
        )
    );

ALTER TABLE submissions
    ADD CONSTRAINT ck_submissions_review_status CHECK (
        review_status IN ('PENDING_REVIEW', 'FLAGGED', 'APPROVED')
    );

ALTER TABLE submissions
    ADD CONSTRAINT ck_submissions_reviewer CHECK (
        reviewed_by_user_id IS NULL OR reviewed_by_user_id > 0
    );

ALTER TABLE submissions
    ADD CONSTRAINT ck_submissions_approval_state CHECK (
        (
            review_status = 'PENDING_REVIEW'
            AND approved_marks IS NULL
            AND approved_feedback IS NULL
            AND reviewed_by_user_id IS NULL
            AND reviewed_at IS NULL
        )
        OR
        (
            review_status = 'FLAGGED'
            AND approved_marks IS NULL
            AND approved_feedback IS NULL
            AND reviewed_by_user_id IS NOT NULL
            AND reviewed_at IS NOT NULL
        )
        OR
        (
            review_status = 'APPROVED'
            AND approved_marks IS NOT NULL
            AND approved_marks >= 0
            AND approved_marks <= max_marks
            AND approved_feedback IS NOT NULL
            AND TRIM(approved_feedback) <> ''
            AND reviewed_by_user_id IS NOT NULL
            AND reviewed_at IS NOT NULL
        )
    );

CREATE TABLE answer_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id BIGINT NOT NULL,
    action VARCHAR(24) NOT NULL,
    reviewer_user_id BIGINT NOT NULL,
    previous_status VARCHAR(24) NOT NULL,
    new_status VARCHAR(24) NOT NULL,
    previous_marks DECIMAL(6, 2),
    new_marks DECIMAL(6, 2),
    previous_feedback TEXT,
    new_feedback TEXT,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_answer_reviews_action CHECK (
        action IN ('APPROVED', 'REVISED', 'FLAGGED', 'RESET_TO_AI')
    ),
    CONSTRAINT ck_answer_reviews_reviewer CHECK (reviewer_user_id > 0),
    CONSTRAINT ck_answer_reviews_previous_status CHECK (
        previous_status IN ('PENDING_REVIEW', 'FLAGGED', 'APPROVED')
    ),
    CONSTRAINT ck_answer_reviews_new_status CHECK (
        new_status IN ('PENDING_REVIEW', 'FLAGGED', 'APPROVED')
    ),
    CONSTRAINT ck_answer_reviews_previous_marks CHECK (
        previous_marks IS NULL OR previous_marks >= 0
    ),
    CONSTRAINT ck_answer_reviews_new_marks CHECK (
        new_marks IS NULL OR new_marks >= 0
    ),
    CONSTRAINT fk_answer_reviews_submission FOREIGN KEY (submission_id)
        REFERENCES submissions (id) ON DELETE CASCADE
);

CREATE INDEX idx_submissions_document
    ON submissions (submission_document_id, worksheet_question_id);

CREATE INDEX idx_submissions_student_review
    ON submissions (student_id, review_status, created_at DESC);

CREATE INDEX idx_answer_reviews_submission_created
    ON answer_reviews (submission_id, created_at, id);
