CREATE TABLE mistake_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    worksheet_id BIGINT NOT NULL,
    worksheet_question_id BIGINT NOT NULL,
    question_bank_id BIGINT NOT NULL,
    syllabus_topic_id BIGINT,
    syllabus_topic_code VARCHAR(120),
    mistake_type VARCHAR(40) NOT NULL,
    description TEXT NOT NULL,
    tutor_note TEXT,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_mistake_records_answer_type UNIQUE (submission_id, mistake_type),
    CONSTRAINT ck_mistake_records_submission CHECK (submission_id > 0),
    CONSTRAINT ck_mistake_records_student CHECK (student_id > 0),
    CONSTRAINT ck_mistake_records_worksheet CHECK (worksheet_id > 0),
    CONSTRAINT ck_mistake_records_question CHECK (worksheet_question_id > 0),
    CONSTRAINT ck_mistake_records_question_bank CHECK (question_bank_id > 0),
    CONSTRAINT ck_mistake_records_topic CHECK (
        (syllabus_topic_id IS NULL AND syllabus_topic_code IS NULL)
        OR (
            syllabus_topic_id > 0
            AND syllabus_topic_code IS NOT NULL
            AND TRIM(syllabus_topic_code) <> ''
        )
    ),
    CONSTRAINT ck_mistake_records_type CHECK (
        mistake_type IN (
            'CONCEPT_MISUNDERSTANDING',
            'CALCULATION_ERROR',
            'MISREAD_QUESTION',
            'INCOMPLETE_WORKING',
            'INCORRECT_FORMULA',
            'CARELESS_MISTAKE',
            'WEAK_EXPLANATION',
            'MISSING_KEY_POINT',
            'WRONG_UNITS',
            'ANSWER_FORMAT_ISSUE'
        )
    ),
    CONSTRAINT ck_mistake_records_description CHECK (TRIM(description) <> ''),
    CONSTRAINT fk_mistake_records_submission FOREIGN KEY (submission_id)
        REFERENCES submissions (id) ON DELETE CASCADE
);

CREATE INDEX idx_mistake_records_student_type_created
    ON mistake_records (student_id, mistake_type, created_at DESC, id DESC);

CREATE INDEX idx_mistake_records_student_topic_created
    ON mistake_records (student_id, syllabus_topic_id, created_at DESC, id DESC);

CREATE INDEX idx_mistake_records_submission_created
    ON mistake_records (submission_id, created_at, id);
