CREATE TABLE ocr_extractions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_page_id BIGINT NOT NULL UNIQUE,
    worksheet_question_id BIGINT,
    extracted_text TEXT NOT NULL,
    corrected_text TEXT,
    confidence NUMERIC(5,4) NOT NULL,
    status VARCHAR(16) NOT NULL,
    provider VARCHAR(80) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ocr_extractions_page FOREIGN KEY (submission_page_id) REFERENCES submission_pages(id) ON DELETE CASCADE,
    CONSTRAINT ck_ocr_extractions_confidence CHECK (confidence >= 0 AND confidence <= 1),
    CONSTRAINT ck_ocr_extractions_status CHECK (status IN ('READY', 'REQUIRES_REVIEW', 'UNREADABLE'))
);
