ALTER TABLE submissions ADD COLUMN syllabus_topic_id BIGINT;
ALTER TABLE submissions ADD COLUMN syllabus_topic_code VARCHAR(120);
ALTER TABLE submissions ADD COLUMN mastery_sync_revision BIGINT NOT NULL DEFAULT 0;

CREATE TABLE approved_diagnostic_evidence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id BIGINT NOT NULL,
    position INTEGER NOT NULL,
    syllabus_topic_id BIGINT NOT NULL,
    category VARCHAR(24) NOT NULL,
    description TEXT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_approved_diagnostic_evidence_position UNIQUE (submission_id, position),
    CONSTRAINT ck_approved_diagnostic_evidence_position CHECK (position >= 0),
    CONSTRAINT ck_approved_diagnostic_evidence_topic CHECK (syllabus_topic_id > 0),
    CONSTRAINT ck_approved_diagnostic_evidence_category CHECK (category IN ('CONCEPT', 'KEYWORD', 'EXPRESSION', 'APPLICATION')),
    CONSTRAINT ck_approved_diagnostic_evidence_description CHECK (TRIM(description) <> ''),
    CONSTRAINT fk_approved_diagnostic_evidence_submission FOREIGN KEY (submission_id)
        REFERENCES submissions (id) ON DELETE CASCADE
);

CREATE TABLE approved_diagnostic_evidence_keywords (
    evidence_id BIGINT NOT NULL,
    position INTEGER NOT NULL,
    keyword VARCHAR(180) NOT NULL,
    CONSTRAINT pk_approved_diagnostic_evidence_keywords PRIMARY KEY (evidence_id, position),
    CONSTRAINT ck_approved_diagnostic_evidence_keyword CHECK (TRIM(keyword) <> ''),
    CONSTRAINT fk_approved_diagnostic_evidence_keywords_evidence FOREIGN KEY (evidence_id)
        REFERENCES approved_diagnostic_evidence (id) ON DELETE CASCADE
);

CREATE TABLE mastery_sync_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_key VARCHAR(120) NOT NULL,
    event_type VARCHAR(32) NOT NULL,
    payload TEXT NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    last_error TEXT,
    delivered_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_mastery_sync_outbox_event UNIQUE (event_key),
    CONSTRAINT ck_mastery_sync_outbox_event_type CHECK (event_type IN ('APPROVED_MARKING', 'MARKING_REVIEW_STATE')),
    CONSTRAINT ck_mastery_sync_outbox_attempts CHECK (attempt_count >= 0),
    CONSTRAINT ck_mastery_sync_outbox_payload CHECK (TRIM(payload) <> '')
);

CREATE INDEX idx_mastery_sync_outbox_pending ON mastery_sync_outbox (delivered_at, id);
