CREATE TABLE progress_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tutor_id BIGINT NOT NULL,
    student_profile_id BIGINT NOT NULL,
    report_code VARCHAR(120) NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    report_status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    snapshot TEXT NOT NULL,
    generated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finalized_at TIMESTAMP(6),
    finalized_by_user_id BIGINT,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_progress_reports_student_code UNIQUE (student_profile_id, report_code),
    CONSTRAINT ck_progress_reports_tutor CHECK (tutor_id > 0),
    CONSTRAINT ck_progress_reports_code CHECK (
        TRIM(report_code) <> '' AND report_code = UPPER(TRIM(report_code))
    ),
    CONSTRAINT ck_progress_reports_period CHECK (period_start <= period_end),
    CONSTRAINT ck_progress_reports_status CHECK (report_status IN ('DRAFT', 'FINAL')),
    CONSTRAINT ck_progress_reports_snapshot CHECK (TRIM(snapshot) <> ''),
    CONSTRAINT ck_progress_reports_final CHECK (
        (report_status = 'DRAFT' AND finalized_at IS NULL AND finalized_by_user_id IS NULL)
        OR
        (report_status = 'FINAL' AND finalized_at IS NOT NULL
            AND finalized_by_user_id IS NOT NULL)
    ),
    CONSTRAINT ck_progress_reports_finalizer CHECK (
        finalized_by_user_id IS NULL OR finalized_by_user_id > 0
    ),
    CONSTRAINT fk_progress_reports_student FOREIGN KEY (student_profile_id)
        REFERENCES student_profiles (id) ON DELETE RESTRICT
);

CREATE INDEX idx_progress_reports_tutor_status
    ON progress_reports (tutor_id, report_status, period_end DESC);

CREATE INDEX idx_progress_reports_student_period
    ON progress_reports (student_profile_id, period_end DESC, id DESC);
