CREATE TABLE class_topic_coverage (
    class_id BIGINT NOT NULL,
    topic_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (class_id, topic_id),
    CONSTRAINT fk_class_topic_coverage_class FOREIGN KEY (class_id)
        REFERENCES tutor_classes (id) ON DELETE CASCADE,
    CONSTRAINT fk_class_topic_coverage_topic FOREIGN KEY (topic_id)
        REFERENCES syllabus_topics (id) ON DELETE RESTRICT
);

CREATE TABLE class_insight_settings (
    class_id BIGINT PRIMARY KEY,
    weak_average_mastery_percent DECIMAL(5,2) NOT NULL DEFAULT 70.00,
    weak_student_ratio_percent DECIMAL(5,2) NOT NULL DEFAULT 40.00,
    minimum_active_students INTEGER NOT NULL DEFAULT 3,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_class_insight_settings_average CHECK (weak_average_mastery_percent >= 0 AND weak_average_mastery_percent <= 100),
    CONSTRAINT ck_class_insight_settings_ratio CHECK (weak_student_ratio_percent >= 0 AND weak_student_ratio_percent <= 100),
    CONSTRAINT ck_class_insight_settings_minimum CHECK (minimum_active_students >= 1),
    CONSTRAINT fk_class_insight_settings_class FOREIGN KEY (class_id)
        REFERENCES tutor_classes (id) ON DELETE CASCADE
);

CREATE TABLE class_insight_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id BIGINT NOT NULL,
    tutor_id BIGINT NOT NULL,
    fingerprint VARCHAR(64) NOT NULL,
    status VARCHAR(16) NOT NULL,
    data_as_of TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    failure_message VARCHAR(500),
    CONSTRAINT ck_class_insight_snapshots_status CHECK (status IN ('FRESH', 'STALE', 'REFRESHING', 'FAILED')),
    CONSTRAINT fk_class_insight_snapshots_class_owner FOREIGN KEY (class_id, tutor_id)
        REFERENCES tutor_classes (id, tutor_id) ON DELETE CASCADE
);
CREATE INDEX idx_class_insight_snapshots_owner_class_created ON class_insight_snapshots (tutor_id, class_id, created_at DESC, id DESC);

CREATE TABLE class_insight_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_id BIGINT NOT NULL,
    topic_id BIGINT NOT NULL,
    topic_name VARCHAR(160) NOT NULL,
    average_mastery_percent DECIMAL(5,2) NOT NULL,
    active_student_count INTEGER NOT NULL,
    assessed_student_count INTEGER NOT NULL,
    affected_student_count INTEGER NOT NULL,
    weak BOOLEAN NOT NULL,
    suggested_action VARCHAR(500) NOT NULL,
    CONSTRAINT uk_class_insight_items_snapshot_topic UNIQUE (snapshot_id, topic_id),
    CONSTRAINT fk_class_insight_items_snapshot FOREIGN KEY (snapshot_id)
        REFERENCES class_insight_snapshots (id) ON DELETE CASCADE,
    CONSTRAINT fk_class_insight_items_topic FOREIGN KEY (topic_id)
        REFERENCES syllabus_topics (id) ON DELETE RESTRICT
);

CREATE TABLE class_insight_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_id BIGINT NOT NULL,
    tutor_id BIGINT NOT NULL,
    feedback VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_class_insight_feedback_text CHECK (TRIM(feedback) <> ''),
    CONSTRAINT fk_class_insight_feedback_snapshot FOREIGN KEY (snapshot_id)
        REFERENCES class_insight_snapshots (id) ON DELETE CASCADE
);

CREATE TABLE class_insight_ranking_overrides (
    class_id BIGINT NOT NULL,
    tutor_id BIGINT NOT NULL,
    topic_id BIGINT NOT NULL,
    display_rank INTEGER NOT NULL,
    note VARCHAR(500),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (class_id, topic_id),
    CONSTRAINT ck_class_insight_ranking_rank CHECK (display_rank >= 1),
    CONSTRAINT fk_class_insight_ranking_class_owner FOREIGN KEY (class_id, tutor_id)
        REFERENCES tutor_classes (id, tutor_id) ON DELETE CASCADE,
    CONSTRAINT fk_class_insight_ranking_topic FOREIGN KEY (topic_id)
        REFERENCES syllabus_topics (id) ON DELETE RESTRICT
);

CREATE TABLE class_insight_refresh_queue (
    class_id BIGINT PRIMARY KEY,
    tutor_id BIGINT NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'QUEUED',
    requested_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMP(6),
    completed_at TIMESTAMP(6),
    last_error VARCHAR(500),
    CONSTRAINT ck_class_insight_refresh_queue_status CHECK (status IN ('QUEUED', 'RUNNING', 'FAILED')),
    CONSTRAINT fk_class_insight_refresh_queue_class_owner FOREIGN KEY (class_id, tutor_id)
        REFERENCES tutor_classes (id, tutor_id) ON DELETE CASCADE
);
