CREATE TABLE tutor_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tutor_id BIGINT NOT NULL,
    student_profile_id BIGINT NOT NULL,
    content VARCHAR(4000) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_tutor_notes_tutor CHECK (tutor_id > 0),
    CONSTRAINT ck_tutor_notes_content CHECK (TRIM(content) <> ''),
    CONSTRAINT fk_tutor_notes_student_owner FOREIGN KEY (student_profile_id, tutor_id)
        REFERENCES student_profiles (id, tutor_id) ON DELETE CASCADE
);

CREATE INDEX idx_tutor_notes_owner_student_updated
    ON tutor_notes (tutor_id, student_profile_id, updated_at DESC, id DESC);
