CREATE TABLE worksheet_generation_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tutor_id BIGINT NOT NULL,
    class_id BIGINT NOT NULL,
    target_mode VARCHAR(16) NOT NULL,
    question_count INTEGER NOT NULL,
    question_type VARCHAR(32),
    due_at TIMESTAMP(6),
    idempotency_key VARCHAR(128) NOT NULL,
    request_hash VARCHAR(128) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'QUEUED',
    failure_code VARCHAR(80),
    failure_message VARCHAR(500),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_worksheet_generation_request_key UNIQUE (tutor_id, idempotency_key),
    CONSTRAINT ck_worksheet_generation_target_mode CHECK (target_mode IN ('CLASS', 'STUDENTS')),
    CONSTRAINT ck_worksheet_generation_count CHECK (question_count BETWEEN 1 AND 100),
    CONSTRAINT ck_worksheet_generation_status CHECK (status IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED')),
    CONSTRAINT fk_worksheet_generation_class FOREIGN KEY (class_id, tutor_id)
        REFERENCES tutor_classes (id, tutor_id) ON DELETE RESTRICT
);

CREATE TABLE worksheet_generation_request_topics (
    request_id BIGINT NOT NULL,
    topic_id BIGINT NOT NULL,
    position INTEGER NOT NULL,
    PRIMARY KEY (request_id, topic_id),
    CONSTRAINT ck_worksheet_generation_topic_position CHECK (position >= 0),
    CONSTRAINT fk_worksheet_generation_topic_request FOREIGN KEY (request_id)
        REFERENCES worksheet_generation_requests (id) ON DELETE CASCADE,
    CONSTRAINT fk_worksheet_generation_topic FOREIGN KEY (topic_id)
        REFERENCES syllabus_topics (id) ON DELETE RESTRICT
);

CREATE TABLE worksheet_generation_request_students (
    request_id BIGINT NOT NULL,
    student_profile_id BIGINT NOT NULL,
    PRIMARY KEY (request_id, student_profile_id),
    CONSTRAINT fk_worksheet_generation_student_request FOREIGN KEY (request_id)
        REFERENCES worksheet_generation_requests (id) ON DELETE CASCADE,
    CONSTRAINT fk_worksheet_generation_student FOREIGN KEY (student_profile_id)
        REFERENCES student_profiles (id) ON DELETE RESTRICT
);

ALTER TABLE worksheets ADD COLUMN generation_request_id BIGINT;
ALTER TABLE worksheets ADD CONSTRAINT fk_worksheets_generation_request
    FOREIGN KEY (generation_request_id) REFERENCES worksheet_generation_requests (id) ON DELETE SET NULL;
CREATE INDEX idx_worksheet_generation_owner_status ON worksheet_generation_requests (tutor_id, status, created_at);
