CREATE TABLE mastery_approved_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_submission_id BIGINT NOT NULL UNIQUE,
    tutor_id BIGINT NOT NULL,
    student_profile_id BIGINT NOT NULL,
    syllabus_topic_id BIGINT NOT NULL,
    approved_marks DECIMAL(6, 2) NOT NULL,
    available_marks DECIMAL(6, 2) NOT NULL,
    repeated_mistake_count INTEGER NOT NULL DEFAULT 0,
    revision INTEGER NOT NULL,
    active BOOLEAN NOT NULL,
    reviewed_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_mastery_approved_results_tutor CHECK (tutor_id > 0),
    CONSTRAINT ck_mastery_approved_results_source CHECK (source_submission_id > 0),
    CONSTRAINT ck_mastery_approved_results_marks CHECK (approved_marks >= 0 AND available_marks > 0 AND approved_marks <= available_marks),
    CONSTRAINT ck_mastery_approved_results_repeated CHECK (repeated_mistake_count >= 0),
    CONSTRAINT ck_mastery_approved_results_revision CHECK (revision > 0),
    CONSTRAINT fk_mastery_approved_results_student FOREIGN KEY (student_profile_id)
        REFERENCES student_profiles (id) ON DELETE CASCADE,
    CONSTRAINT fk_mastery_approved_results_topic FOREIGN KEY (syllabus_topic_id)
        REFERENCES syllabus_topics (id) ON DELETE RESTRICT
);

CREATE INDEX idx_mastery_approved_results_topic_active
    ON mastery_approved_results (student_profile_id, syllabus_topic_id, active, reviewed_at, source_submission_id);

CREATE TABLE mastery_diagnostic_evidence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mastery_record_id BIGINT NOT NULL,
    student_profile_id BIGINT NOT NULL,
    tutor_id BIGINT NOT NULL,
    source_submission_id BIGINT NOT NULL,
    diagnostic_category VARCHAR(16) NOT NULL,
    tutor_rationale VARCHAR(500) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_mastery_diagnostic_evidence_submission_category
        UNIQUE (source_submission_id, diagnostic_category),
    CONSTRAINT ck_mastery_diagnostic_evidence_tutor CHECK (tutor_id > 0),
    CONSTRAINT ck_mastery_diagnostic_evidence_submission CHECK (source_submission_id > 0),
    CONSTRAINT ck_mastery_diagnostic_evidence_category CHECK (
        diagnostic_category IN ('CONCEPT', 'KEYWORD', 'EXPRESSION', 'APPLICATION')
    ),
    CONSTRAINT ck_mastery_diagnostic_evidence_rationale CHECK (TRIM(tutor_rationale) <> ''),
    CONSTRAINT fk_mastery_diagnostic_evidence_record FOREIGN KEY (mastery_record_id)
        REFERENCES mastery_records (id) ON DELETE CASCADE,
    CONSTRAINT fk_mastery_diagnostic_evidence_student FOREIGN KEY (student_profile_id)
        REFERENCES student_profiles (id) ON DELETE CASCADE
);

CREATE TABLE mastery_diagnostic_evidence_keywords (
    evidence_id BIGINT NOT NULL,
    keyword_position INTEGER NOT NULL,
    keyword VARCHAR(120) NOT NULL,
    PRIMARY KEY (evidence_id, keyword_position),
    CONSTRAINT ck_mastery_diagnostic_keyword_position CHECK (keyword_position >= 0),
    CONSTRAINT ck_mastery_diagnostic_keyword CHECK (TRIM(keyword) <> ''),
    CONSTRAINT fk_mastery_diagnostic_keyword_evidence FOREIGN KEY (evidence_id)
        REFERENCES mastery_diagnostic_evidence (id) ON DELETE CASCADE
);

CREATE INDEX idx_mastery_diagnostic_evidence_student_topic
    ON mastery_diagnostic_evidence (student_profile_id, mastery_record_id, diagnostic_category, created_at DESC);
