CREATE TABLE question_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL,
    position INTEGER NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    content_type VARCHAR(16) NOT NULL,
    image_bytes BYTEA NOT NULL,
    width INTEGER NOT NULL,
    height INTEGER NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_question_images_position UNIQUE (question_id, position),
    CONSTRAINT ck_question_images_position CHECK (position >= 0),
    CONSTRAINT ck_question_images_content_type CHECK (content_type IN ('image/png', 'image/jpeg')),
    CONSTRAINT ck_question_images_dimensions CHECK (width > 0 AND height > 0),
    CONSTRAINT fk_question_images_question FOREIGN KEY (question_id)
        REFERENCES questions (id) ON DELETE CASCADE
);

CREATE INDEX idx_question_images_question ON question_images (question_id, position);

-- Worksheet images are an immutable copy.  A later replacement or deletion in
-- the Question Bank must never change a generated worksheet or historical PDF.
CREATE TABLE worksheet_question_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worksheet_question_id BIGINT NOT NULL,
    position INTEGER NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    content_type VARCHAR(16) NOT NULL,
    image_bytes BYTEA NOT NULL,
    width INTEGER NOT NULL,
    height INTEGER NOT NULL,
    CONSTRAINT uk_worksheet_question_images_position UNIQUE (worksheet_question_id, position),
    CONSTRAINT ck_worksheet_question_images_position CHECK (position >= 0),
    CONSTRAINT ck_worksheet_question_images_content_type CHECK (content_type IN ('image/png', 'image/jpeg')),
    CONSTRAINT ck_worksheet_question_images_dimensions CHECK (width > 0 AND height > 0),
    CONSTRAINT fk_worksheet_question_images_question FOREIGN KEY (worksheet_question_id)
        REFERENCES worksheet_questions (id) ON DELETE CASCADE
);
