-- A batch is deliberately separate from the canonical question bank.  OCR is
-- advisory evidence and must be reviewed by a tutor before it can create a
-- question that is eligible for worksheet generation.
CREATE TABLE question_import_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_filename VARCHAR(255) NOT NULL,
    status VARCHAR(24) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_question_import_batch_status CHECK (status IN ('READY_FOR_REVIEW', 'FAILED', 'IMPORTED'))
);

CREATE TABLE question_import_source_pages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL,
    source_filename VARCHAR(255) NOT NULL,
    source_page_number INTEGER NOT NULL,
    content_type VARCHAR(16) NOT NULL,
    page_image_bytes BYTEA NOT NULL,
    width INTEGER NOT NULL,
    height INTEGER NOT NULL,
    extracted_text VARCHAR(12000) NOT NULL DEFAULT '',
    processing_error VARCHAR(1000),
    CONSTRAINT uk_question_import_page UNIQUE (batch_id, source_filename, source_page_number),
    CONSTRAINT ck_question_import_page_number CHECK (source_page_number >= 1),
    CONSTRAINT ck_question_import_page_content_type CHECK (content_type IN ('image/png', 'image/jpeg')),
    CONSTRAINT ck_question_import_page_dimensions CHECK (width > 0 AND height > 0),
    CONSTRAINT fk_question_import_page_batch FOREIGN KEY (batch_id)
        REFERENCES question_import_batches (id) ON DELETE CASCADE
);

CREATE TABLE question_import_candidates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL,
    source_page_id BIGINT NOT NULL,
    candidate_number INTEGER NOT NULL,
    status VARCHAR(24) NOT NULL,
    confidence INTEGER NOT NULL,
    warning_message VARCHAR(1000),
    suggested_question_type VARCHAR(32) NOT NULL,
    suggested_difficulty VARCHAR(16) NOT NULL,
    suggested_tags VARCHAR(1000) NOT NULL DEFAULT '',
    question_code VARCHAR(120),
    syllabus_topic_id BIGINT,
    prompt VARCHAR(4000) NOT NULL DEFAULT '',
    model_answer VARCHAR(4000) NOT NULL DEFAULT '',
    total_marks NUMERIC(6,2) NOT NULL DEFAULT 1.00,
    include_source_image BOOLEAN NOT NULL DEFAULT TRUE,
    imported_question_id BIGINT,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_question_import_candidate_number UNIQUE (source_page_id, candidate_number),
    CONSTRAINT ck_question_import_candidate_status CHECK (status IN ('READY_FOR_REVIEW', 'UNCERTAIN', 'FAILED', 'IMPORTED')),
    CONSTRAINT ck_question_import_candidate_confidence CHECK (confidence >= 0 AND confidence <= 100),
    CONSTRAINT ck_question_import_candidate_marks CHECK (total_marks > 0),
    CONSTRAINT fk_question_import_candidate_batch FOREIGN KEY (batch_id)
        REFERENCES question_import_batches (id) ON DELETE CASCADE,
    CONSTRAINT fk_question_import_candidate_page FOREIGN KEY (source_page_id)
        REFERENCES question_import_source_pages (id) ON DELETE CASCADE,
    CONSTRAINT fk_question_import_candidate_topic FOREIGN KEY (syllabus_topic_id)
        REFERENCES syllabus_topics (id),
    CONSTRAINT fk_question_import_candidate_question FOREIGN KEY (imported_question_id)
        REFERENCES questions (id)
);

CREATE INDEX idx_question_import_pages_batch ON question_import_source_pages (batch_id, source_filename, source_page_number);
CREATE INDEX idx_question_import_candidates_batch ON question_import_candidates (batch_id, status, source_page_id, candidate_number);
