-- Crops are retained review evidence.  They are generated locally from the
-- persisted page pixels and never from OCR text or an image-generation model.
CREATE TABLE question_import_diagram_crops (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL,
    source_page_id BIGINT NOT NULL,
    candidate_id BIGINT NOT NULL,
    diagram_region_id VARCHAR(64) NOT NULL,
    sub_question_id VARCHAR(64),
    x INTEGER NOT NULL,
    y INTEGER NOT NULL,
    width INTEGER NOT NULL,
    height INTEGER NOT NULL,
    content_type VARCHAR(16) NOT NULL,
    crop_image_bytes BYTEA NOT NULL,
    crop_width INTEGER NOT NULL,
    crop_height INTEGER NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_question_import_crop_region UNIQUE (candidate_id, diagram_region_id),
    CONSTRAINT ck_question_import_crop_content_type CHECK (content_type = 'image/png'),
    CONSTRAINT ck_question_import_crop_rectangle CHECK (x >= 0 AND y >= 0 AND width > 0 AND height > 0),
    CONSTRAINT ck_question_import_crop_dimensions CHECK (crop_width > 0 AND crop_height > 0),
    CONSTRAINT fk_question_import_crop_batch FOREIGN KEY (batch_id)
        REFERENCES question_import_batches (id) ON DELETE CASCADE,
    CONSTRAINT fk_question_import_crop_page FOREIGN KEY (source_page_id)
        REFERENCES question_import_source_pages (id) ON DELETE CASCADE,
    CONSTRAINT fk_question_import_crop_candidate FOREIGN KEY (candidate_id)
        REFERENCES question_import_candidates (id) ON DELETE CASCADE
);

CREATE INDEX idx_question_import_crops_batch_candidate
    ON question_import_diagram_crops (batch_id, candidate_id, diagram_region_id);
