CREATE TABLE tutor_classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tutor_id BIGINT NOT NULL,
    class_name VARCHAR(120) NOT NULL,
    normalized_class_name VARCHAR(120) NOT NULL,
    subject VARCHAR(80) NOT NULL,
    class_level VARCHAR(40) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_tutor_classes_owner CHECK (tutor_id > 0),
    CONSTRAINT ck_tutor_classes_name CHECK (TRIM(class_name) <> ''),
    CONSTRAINT ck_tutor_classes_subject CHECK (TRIM(subject) <> ''),
    CONSTRAINT ck_tutor_classes_level CHECK (TRIM(class_level) <> ''),
    CONSTRAINT ck_tutor_classes_status CHECK (status IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT uk_tutor_classes_owner_name UNIQUE (tutor_id, normalized_class_name)
);

CREATE TABLE class_schedules (
    class_id BIGINT NOT NULL,
    day_of_week VARCHAR(9) NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    CONSTRAINT pk_class_schedules PRIMARY KEY (class_id, day_of_week, start_time, end_time),
    CONSTRAINT ck_class_schedules_day CHECK (
        day_of_week IN (
            'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY',
            'FRIDAY', 'SATURDAY', 'SUNDAY'
        )
    ),
    CONSTRAINT ck_class_schedules_time CHECK (start_time < end_time),
    CONSTRAINT fk_class_schedules_class FOREIGN KEY (class_id)
        REFERENCES tutor_classes (id) ON DELETE CASCADE
);

CREATE INDEX idx_tutor_classes_owner_status
    ON tutor_classes (tutor_id, status);

CREATE INDEX idx_class_schedules_class
    ON class_schedules (class_id);
