ALTER TABLE tutor_classes
    ADD CONSTRAINT uk_tutor_classes_id_owner UNIQUE (id, tutor_id);

CREATE TABLE student_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tutor_id BIGINT NOT NULL,
    login_user_id BIGINT,
    full_name VARCHAR(120) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_student_profiles_owner CHECK (tutor_id > 0),
    CONSTRAINT ck_student_profiles_login CHECK (login_user_id IS NULL OR login_user_id > 0),
    CONSTRAINT ck_student_profiles_name CHECK (TRIM(full_name) <> ''),
    CONSTRAINT uk_student_profiles_login UNIQUE (login_user_id),
    CONSTRAINT uk_student_profiles_id_owner UNIQUE (id, tutor_id)
);

CREATE TABLE class_memberships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_profile_id BIGINT NOT NULL,
    class_id BIGINT NOT NULL,
    tutor_id BIGINT NOT NULL,
    joined_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_class_memberships_owner CHECK (tutor_id > 0),
    CONSTRAINT uk_class_memberships_student_class UNIQUE (student_profile_id, class_id),
    CONSTRAINT fk_class_memberships_student_owner FOREIGN KEY (student_profile_id, tutor_id)
        REFERENCES student_profiles (id, tutor_id) ON DELETE CASCADE,
    CONSTRAINT fk_class_memberships_class_owner FOREIGN KEY (class_id, tutor_id)
        REFERENCES tutor_classes (id, tutor_id) ON DELETE RESTRICT
);

CREATE INDEX idx_student_profiles_owner
    ON student_profiles (tutor_id);

CREATE INDEX idx_class_memberships_class
    ON class_memberships (class_id);

