CREATE TABLE syllabus_topics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(120) NOT NULL,
    name VARCHAR(160) NOT NULL,
    node_type VARCHAR(16) NOT NULL,
    depth SMALLINT NOT NULL,
    parent_id BIGINT,
    parent_depth SMALLINT,
    sort_order INTEGER NOT NULL,
    curriculum_version VARCHAR(80) NOT NULL,
    source_reference VARCHAR(500) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_syllabus_topics_code UNIQUE (code),
    CONSTRAINT uk_syllabus_topics_id_depth UNIQUE (id, depth),
    CONSTRAINT uk_syllabus_topics_parent_order UNIQUE (parent_id, sort_order),
    CONSTRAINT uk_syllabus_topics_parent_name UNIQUE (parent_id, name),
    CONSTRAINT ck_syllabus_topics_code CHECK (TRIM(code) <> ''),
    CONSTRAINT ck_syllabus_topics_name CHECK (TRIM(name) <> ''),
    CONSTRAINT ck_syllabus_topics_sort_order CHECK (sort_order >= 0),
    CONSTRAINT ck_syllabus_topics_version CHECK (TRIM(curriculum_version) <> ''),
    CONSTRAINT ck_syllabus_topics_source CHECK (TRIM(source_reference) <> ''),
    CONSTRAINT ck_syllabus_topics_hierarchy CHECK (
        (node_type = 'SUBJECT' AND depth = 0 AND parent_id IS NULL AND parent_depth IS NULL)
        OR
        (node_type = 'LEVEL' AND depth = 1 AND parent_id IS NOT NULL AND parent_depth = 0)
        OR
        (node_type = 'THEME' AND depth = 2 AND parent_id IS NOT NULL AND parent_depth = 1)
        OR
        (node_type = 'TOPIC' AND depth = 3 AND parent_id IS NOT NULL AND parent_depth = 2)
        OR
        (node_type = 'SUBTOPIC' AND depth = 4 AND parent_id IS NOT NULL AND parent_depth = 3)
    ),
    CONSTRAINT fk_syllabus_topics_parent_depth FOREIGN KEY (parent_id, parent_depth)
        REFERENCES syllabus_topics (id, depth) ON DELETE RESTRICT
);

CREATE INDEX idx_syllabus_topics_parent_order
    ON syllabus_topics (parent_id, sort_order, code);

CREATE INDEX idx_syllabus_topics_type
    ON syllabus_topics (node_type, active);

CREATE INDEX idx_syllabus_topics_version
    ON syllabus_topics (curriculum_version, active);
