ALTER TABLE syllabus_topics
    ADD CONSTRAINT uk_syllabus_topics_id_node_type UNIQUE (id, node_type);

CREATE TABLE questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(120) NOT NULL,
    syllabus_topic_id BIGINT NOT NULL,
    syllabus_topic_type VARCHAR(16) NOT NULL,
    question_type VARCHAR(32) NOT NULL,
    prompt VARCHAR(4000) NOT NULL,
    total_marks DECIMAL(6, 2) NOT NULL,
    model_answer VARCHAR(4000) NOT NULL,
    archive_state VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_questions_code UNIQUE (code),
    CONSTRAINT ck_questions_code CHECK (
        TRIM(code) <> '' AND code = UPPER(TRIM(code))
    ),
    CONSTRAINT ck_questions_taxonomy_type CHECK (
        syllabus_topic_type IN ('TOPIC', 'SUBTOPIC')
    ),
    CONSTRAINT ck_questions_type CHECK (
        question_type IN (
            'MULTIPLE_CHOICE',
            'TRUE_FALSE',
            'FILL_IN_THE_BLANK',
            'SHORT_ANSWER',
            'OPEN_ENDED',
            'CALCULATION',
            'DIAGRAM'
        )
    ),
    CONSTRAINT ck_questions_prompt CHECK (TRIM(prompt) <> ''),
    CONSTRAINT ck_questions_total_marks CHECK (total_marks > 0),
    CONSTRAINT ck_questions_model_answer CHECK (TRIM(model_answer) <> ''),
    CONSTRAINT ck_questions_archive_state CHECK (
        archive_state IN ('ACTIVE', 'ARCHIVED')
    ),
    CONSTRAINT fk_questions_syllabus_topic FOREIGN KEY (
        syllabus_topic_id,
        syllabus_topic_type
    ) REFERENCES syllabus_topics (id, node_type) ON DELETE RESTRICT
);

CREATE TABLE marking_components (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL,
    position INTEGER NOT NULL,
    description VARCHAR(1000) NOT NULL,
    marks DECIMAL(6, 2) NOT NULL,
    CONSTRAINT uk_marking_components_position UNIQUE (question_id, position),
    CONSTRAINT ck_marking_components_position CHECK (position >= 0),
    CONSTRAINT ck_marking_components_description CHECK (TRIM(description) <> ''),
    CONSTRAINT ck_marking_components_marks CHECK (marks > 0),
    CONSTRAINT fk_marking_components_question FOREIGN KEY (question_id)
        REFERENCES questions (id) ON DELETE CASCADE
);

CREATE TABLE question_keywords (
    question_id BIGINT NOT NULL,
    position INTEGER NOT NULL,
    keyword VARCHAR(80) NOT NULL,
    CONSTRAINT pk_question_keywords PRIMARY KEY (question_id, position),
    CONSTRAINT uk_question_keywords_value UNIQUE (question_id, keyword),
    CONSTRAINT ck_question_keywords_position CHECK (position >= 0),
    CONSTRAINT ck_question_keywords_value CHECK (
        TRIM(keyword) <> '' AND keyword = LOWER(TRIM(keyword))
    ),
    CONSTRAINT fk_question_keywords_question FOREIGN KEY (question_id)
        REFERENCES questions (id) ON DELETE CASCADE
);

CREATE INDEX idx_questions_taxonomy_active
    ON questions (syllabus_topic_id, archive_state, question_type);

CREATE INDEX idx_questions_type_active
    ON questions (question_type, archive_state);

CREATE INDEX idx_marking_components_question
    ON marking_components (question_id, position);
