CREATE TABLE worksheets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tutor_id BIGINT NOT NULL,
    code VARCHAR(120) NOT NULL,
    title VARCHAR(200) NOT NULL,
    instructions VARCHAR(2000),
    audience_type VARCHAR(16) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    approved_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_worksheets_owner_code UNIQUE (tutor_id, code),
    CONSTRAINT uk_worksheets_id_owner_audience UNIQUE (id, tutor_id, audience_type),
    CONSTRAINT ck_worksheets_owner CHECK (tutor_id > 0),
    CONSTRAINT ck_worksheets_code CHECK (
        TRIM(code) <> '' AND code = UPPER(TRIM(code))
    ),
    CONSTRAINT ck_worksheets_title CHECK (TRIM(title) <> ''),
    CONSTRAINT ck_worksheets_instructions CHECK (
        instructions IS NULL OR TRIM(instructions) <> ''
    ),
    CONSTRAINT ck_worksheets_audience CHECK (
        audience_type IN ('CLASS', 'STUDENT')
    ),
    CONSTRAINT ck_worksheets_status CHECK (
        status IN ('DRAFT', 'APPROVED', 'ARCHIVED')
    ),
    CONSTRAINT ck_worksheets_approval CHECK (
        (status = 'DRAFT' AND approved_at IS NULL)
        OR
        (status IN ('APPROVED', 'ARCHIVED') AND approved_at IS NOT NULL)
    )
);

CREATE TABLE worksheet_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worksheet_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    position INTEGER NOT NULL,
    CONSTRAINT uk_worksheet_questions_question UNIQUE (worksheet_id, question_id),
    CONSTRAINT ck_worksheet_questions_position CHECK (position >= 0),
    CONSTRAINT fk_worksheet_questions_worksheet FOREIGN KEY (worksheet_id)
        REFERENCES worksheets (id) ON DELETE CASCADE,
    CONSTRAINT fk_worksheet_questions_question FOREIGN KEY (question_id)
        REFERENCES questions (id) ON DELETE RESTRICT
);

CREATE TABLE worksheet_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worksheet_id BIGINT NOT NULL,
    tutor_id BIGINT NOT NULL,
    assignment_type VARCHAR(16) NOT NULL,
    target_id BIGINT NOT NULL,
    class_id BIGINT,
    student_profile_id BIGINT,
    assigned_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    due_at TIMESTAMP(6),
    CONSTRAINT uk_worksheet_assignments_target UNIQUE (
        worksheet_id,
        assignment_type,
        target_id
    ),
    CONSTRAINT ck_worksheet_assignments_owner CHECK (tutor_id > 0),
    CONSTRAINT ck_worksheet_assignments_target_id CHECK (target_id > 0),
    CONSTRAINT ck_worksheet_assignments_target CHECK (
        (
            assignment_type = 'CLASS'
            AND class_id = target_id
            AND student_profile_id IS NULL
        )
        OR
        (
            assignment_type = 'STUDENT'
            AND student_profile_id = target_id
            AND class_id IS NULL
        )
    ),
    CONSTRAINT ck_worksheet_assignments_due CHECK (
        due_at IS NULL OR due_at > assigned_at
    ),
    CONSTRAINT fk_worksheet_assignments_worksheet FOREIGN KEY (
        worksheet_id,
        tutor_id,
        assignment_type
    ) REFERENCES worksheets (id, tutor_id, audience_type) ON DELETE RESTRICT,
    CONSTRAINT fk_worksheet_assignments_class FOREIGN KEY (class_id, tutor_id)
        REFERENCES tutor_classes (id, tutor_id) ON DELETE RESTRICT,
    CONSTRAINT fk_worksheet_assignments_student FOREIGN KEY (student_profile_id, tutor_id)
        REFERENCES student_profiles (id, tutor_id) ON DELETE RESTRICT
);

CREATE INDEX idx_worksheets_owner_status
    ON worksheets (tutor_id, status, title);

CREATE INDEX idx_worksheet_questions_order
    ON worksheet_questions (worksheet_id, position, id);

CREATE INDEX idx_worksheet_assignments_class
    ON worksheet_assignments (class_id, assigned_at);

CREATE INDEX idx_worksheet_assignments_student
    ON worksheet_assignments (student_profile_id, assigned_at);
