CREATE TABLE mastery_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_profile_id BIGINT NOT NULL,
    syllabus_topic_id BIGINT NOT NULL,
    score DECIMAL(5, 2) NOT NULL DEFAULT 0,
    mastery_status VARCHAR(16) NOT NULL DEFAULT 'NOT_STARTED',
    attempt_count INTEGER NOT NULL DEFAULT 0,
    last_source_submission_id BIGINT,
    calculated_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_mastery_records_student_topic UNIQUE (student_profile_id, syllabus_topic_id),
    CONSTRAINT ck_mastery_records_score CHECK (score >= 0 AND score <= 100),
    CONSTRAINT ck_mastery_records_status CHECK (
        mastery_status IN (
            'NOT_STARTED', 'LEARNING', 'PRACTISING',
            'IMPROVING', 'MASTERED', 'NEEDS_REVISION'
        )
    ),
    CONSTRAINT ck_mastery_records_attempts CHECK (attempt_count >= 0),
    CONSTRAINT ck_mastery_records_source CHECK (
        last_source_submission_id IS NULL OR last_source_submission_id > 0
    ),
    CONSTRAINT fk_mastery_records_student FOREIGN KEY (student_profile_id)
        REFERENCES student_profiles (id) ON DELETE CASCADE,
    CONSTRAINT fk_mastery_records_topic FOREIGN KEY (syllabus_topic_id)
        REFERENCES syllabus_topics (id) ON DELETE RESTRICT
);

CREATE TABLE mastery_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mastery_record_id BIGINT NOT NULL,
    previous_score DECIMAL(5, 2) NOT NULL,
    new_score DECIMAL(5, 2) NOT NULL,
    previous_status VARCHAR(16) NOT NULL,
    new_status VARCHAR(16) NOT NULL,
    source_submission_id BIGINT NOT NULL,
    reason VARCHAR(500) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_mastery_history_previous_score CHECK (
        previous_score >= 0 AND previous_score <= 100
    ),
    CONSTRAINT ck_mastery_history_new_score CHECK (
        new_score >= 0 AND new_score <= 100
    ),
    CONSTRAINT ck_mastery_history_previous_status CHECK (
        previous_status IN (
            'NOT_STARTED', 'LEARNING', 'PRACTISING',
            'IMPROVING', 'MASTERED', 'NEEDS_REVISION'
        )
    ),
    CONSTRAINT ck_mastery_history_new_status CHECK (
        new_status IN (
            'NOT_STARTED', 'LEARNING', 'PRACTISING',
            'IMPROVING', 'MASTERED', 'NEEDS_REVISION'
        )
    ),
    CONSTRAINT ck_mastery_history_source CHECK (source_submission_id > 0),
    CONSTRAINT ck_mastery_history_reason CHECK (TRIM(reason) <> ''),
    CONSTRAINT fk_mastery_history_record FOREIGN KEY (mastery_record_id)
        REFERENCES mastery_records (id) ON DELETE CASCADE
);

CREATE INDEX idx_mastery_records_student_status
    ON mastery_records (student_profile_id, mastery_status, score DESC);

CREATE INDEX idx_mastery_history_record_created
    ON mastery_history (mastery_record_id, created_at, id);
