CREATE TABLE tutor_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tutor_id BIGINT NOT NULL,
    student_profile_id BIGINT NOT NULL,
    mastery_record_id BIGINT,
    alert_type VARCHAR(32) NOT NULL,
    severity VARCHAR(16) NOT NULL,
    alert_status VARCHAR(16) NOT NULL DEFAULT 'OPEN',
    deduplication_key VARCHAR(200) NOT NULL,
    title VARCHAR(200) NOT NULL,
    message VARCHAR(2000) NOT NULL,
    acknowledged_at TIMESTAMP(6),
    resolved_at TIMESTAMP(6),
    resolved_by_user_id BIGINT,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_tutor_alerts_deduplication UNIQUE (tutor_id, deduplication_key),
    CONSTRAINT ck_tutor_alerts_tutor CHECK (tutor_id > 0),
    CONSTRAINT ck_tutor_alerts_mastery CHECK (
        mastery_record_id IS NULL OR mastery_record_id > 0
    ),
    CONSTRAINT ck_tutor_alerts_type CHECK (
        alert_type IN (
            'WEAK_TOPIC', 'REPEATED_MISTAKE',
            'PENDING_REVIEW', 'REPORT_READY'
        )
    ),
    CONSTRAINT ck_tutor_alerts_severity CHECK (
        severity IN ('INFO', 'WARNING', 'CRITICAL')
    ),
    CONSTRAINT ck_tutor_alerts_status CHECK (
        alert_status IN ('OPEN', 'ACKNOWLEDGED', 'RESOLVED', 'DISMISSED')
    ),
    CONSTRAINT ck_tutor_alerts_key CHECK (TRIM(deduplication_key) <> ''),
    CONSTRAINT ck_tutor_alerts_title CHECK (TRIM(title) <> ''),
    CONSTRAINT ck_tutor_alerts_message CHECK (TRIM(message) <> ''),
    CONSTRAINT ck_tutor_alerts_resolver CHECK (
        resolved_by_user_id IS NULL OR resolved_by_user_id > 0
    ),
    CONSTRAINT ck_tutor_alerts_lifecycle CHECK (
        (alert_status = 'OPEN' AND acknowledged_at IS NULL AND resolved_at IS NULL
            AND resolved_by_user_id IS NULL)
        OR
        (alert_status = 'ACKNOWLEDGED' AND acknowledged_at IS NOT NULL
            AND resolved_at IS NULL AND resolved_by_user_id IS NULL)
        OR
        (alert_status IN ('RESOLVED', 'DISMISSED') AND resolved_at IS NOT NULL
            AND resolved_by_user_id IS NOT NULL)
    ),
    CONSTRAINT fk_tutor_alerts_student FOREIGN KEY (student_profile_id)
        REFERENCES student_profiles (id) ON DELETE CASCADE,
    CONSTRAINT fk_tutor_alerts_mastery FOREIGN KEY (mastery_record_id)
        REFERENCES mastery_records (id) ON DELETE SET NULL
);

CREATE INDEX idx_tutor_alerts_owner_status
    ON tutor_alerts (tutor_id, alert_status, severity, created_at DESC);

CREATE INDEX idx_tutor_alerts_student_created
    ON tutor_alerts (student_profile_id, created_at DESC, id DESC);
